### PR TITLE
XinGitLou

### PR DESCRIPTION
**Pull request by XinGITLou**
Hi coaches~

I have created my student bio, can you please accept my pull request ?

Thank you!

### CODE REVIEW

**Comment by samirm00** [comment]
Hello @XinGITLou, any reason why you didn't use your photo instead of Pullrequest.jpg . I told you to add a new folder `img` to students-bio, not to assets

**Comment by XinGITLou** [comment]
Sorry, i did not see the instruction. I have moved the img to img folder in student-bios.

**Comment by samirm00** [comment]
Cool

**Comment by samirm00** [comment]
> Sorry, i did not see the instruction. I have moved the img to img folder in student-bios.

It is ok, no sorry need we are here to learn.

**Review by samirm00 — APPROVED** [review]
Good to go

**Pull request merged**
